--TODO Дописать Констрейнты
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  state VARCHAR NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1000),
  available BOOLEAN NOT NULL,
  owner_id BIGINT NOT NULL,
  request_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS feedbacks (
  id BIGSERIAL PRIMARY KEY,
  item_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  comment VARCHAR(1000),
  created TIMESTAMP
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGSERIAL PRIMARY KEY,
  description VARCHAR(1000) NOT NULL,
  requester_id BIGINT NOT NULL,
  created TIMESTAMP
);

CREATE TABLE status (
  id INTEGER PRIMARY KEY,
  status VARCHAR
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGSERIAL PRIMARY KEY,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  status_id INTEGER NOT NULL
);



--CREATE TYPE USER AS (
--  id BIGINT,
--  name VARCHAR,
--  email VARCHAR
--);
--
--CREATE TYPE REQUEST AS (
--  id BIGINT,
--  description VARCHAR,
--  requester USER,
--  created TIMESTAMP
--);
--
--CREATE TYPE ITEM AS (
--  id BIGINT,
--  name VARCHAR,
--  description VARCHAR,
--  available BOOLEAN,
--  owner USER,
--  request REQUEST
--);